# -*- coding: utf-8 -*-
"""Traduccion al castellano de la interfaz.

La interfaz del plugin se escribe en INGLES, que es el idioma fuente que
Blender espera, y aqui va el castellano. Blender elige uno u otro segun el
idioma que tenga puesto cada usuario, asi que no hay que duplicar nada.
"""

TRADUCCIONES = {
    "es": {
        ("*", "    'Factor' (it is a number, not a colour)"): "    'Factor' (es un numero, no un color)",
        ("*", "    0 = lows · 1 = highs"): "    0 = graves · 1 = agudos",
        ("*", "    0 = quiet · 1 = full"): "    0 = callado · 1 = a tope",
        ("*", "    Fixed: it does not change with the music."): "    Fijo: no cambia con la musica.",
        ("*", "    How loud its band is on this frame."): "    Cuanto suena su banda en este fotograma.",
        ("*", "    This is the one that reacts."): "    Este es el que reacciona.",
        ("*", "    Where the point sits in the spectrum."): "    Donde cae el punto en el espectro.",
        ("*", "    av_golpe · 0..1, how much the wave hits it now"): "    av_golpe · 0..1, cuanto le da la onda ahora",
        ("*", "    short track: could not check it in chunks"): "    tema corto: no he podido comprobarlo por trozos",
        ("*", "'Highs up to' must be greater than 'Lows from'"): "'Agudos hasta' tiene que ser mayor que 'Graves desde'",
        ("*", "/2"): "/2",
        ("*", "1 is a clean arc from end to end. Adding harmonics puts extra bellies in the string and gives it the whip of a real one"): "Con 1 es un arco limpio de punta a punta. Anadiendo armonicos aparecen mas vientres y la cuerda coge el latigazo de una de verdad",
        ("*", "3. Beat and rhythm"): "3. Compas y ritmo",
        ("*", "4 for a normal 4/4, 3 for a waltz"): "4 para un 4/4 normal, 3 para un vals",
        ("*", "A balance between the two ends of the spectrum, like a tilt equalizer. Towards -1 the lows rule; towards +1 the highs, which are naturally much weaker"): "Una balanza entre los dos extremos del espectro, como un ecualizador de inclinacion. Hacia -1 mandan los graves; hacia +1 los agudos, que de natural son mucho mas debiles",
        ("*", "A cloud of particles orbiting a centre. Each band pushes and lights its own, and the beat waves sweep across it"): "Nube de particulas girando alrededor de un centro. Cada banda empuja y enciende las suyas, y las ondas del compas la barren",
        ("*", "A cloud with volume. More enveloping, but it hides its own particles"): "Nube en volumen. Envuelve mas, pero tapa sus propias particulas",
        ("*", "A current of swirls that drags the cloud along. It removes the perfect-grid feel"): "Una corriente de remolinos que arrastra la nube. Quita el aire de rejilla perfecta",
        ("*", "A flat grid; the points rise and fall like terrain"): "Cuadricula plana; los puntos suben y bajan como un terreno",
        ("*", "A grid of mountains that travels: frequencies across, time along. Each row is a moment of the past"): "Rejilla de montanas que avanza: a lo ancho las frecuencias, a lo largo el tiempo. Cada fila es un instante del pasado",
        ("*", "A notch on the FIRST beat of every bar, hugging one edge. With the ridge alone every beat looks the same and you cannot see where each bar starts; this leaves a lane that acts as a ruler"): "Una muesca en el PRIMER tiempo de cada compas, pegada a una orilla. Con la cresta sola todos los tiempos son iguales y no se ve donde empieza cada compas; esto deja un carril que hace de regla",
        ("*", "A ring leaving the centre on every hit. As well as pushing, it lights the particles it passes. Needs the beat detected"): "Un anillo que sale del centro en cada golpe. Ademas de empujar, enciende las particulas por donde pasa. Necesita el compas detectado",
        ("*", "A ring that leaves the centre on every hit and reaches the rim just as the next one arrives. It reads as rhythm far better than the uniform pulse. Needs the beat detected"): "Un anillo que sale del centro en cada golpe y llega al borde justo cuando entra el siguiente. Se lee como ritmo mucho mejor que el latido uniforme. Necesita el compas detectado",
        ("*", "A row of cubes, one per beat of the bar. On each beat the one that is due grows and lights up, so you can see the rhythm and where you are in the bar"): "Una fila de cubos, uno por tiempo del compas. En cada pulso crece y se enciende el que toca, asi se ve el ritmo y en que tiempo va",
        ("*", "A single peak for all: truer, the lows rule"): "Un unico pico para todas: mas fiel, mandan los graves",
        ("*", "A string that opens pushes its neighbours aside, so the bank stays tight where it is quiet and only spreads where there is energy. This is what lets the strings swing wide without either crossing or leaving a fixed gap everywhere"): "Una cuerda que se abre aparta a sus vecinas, asi que el banco queda apretado donde hay silencio y solo se abre donde hay energia. Es lo que permite que se abran mucho sin cruzarse ni dejar hueco fijo en todas partes",
        ("*", "Above about 4 the AgX view transform washes green and red towards pastel and the VU-meter feel is lost"): "Por encima de ~4 el view transform AgX lava el verde y el rojo hacia el pastel y se pierde el aire de vumetro",
        ("*", "Active"): "Activa",
        ("*", "Active source"): "Fuente activa",
        ("*", "Add a landscape"): "Anadir un paisaje",
        ("*", "Add a plexus"): "Anadir un plexus",
        ("*", "Add a swarm"): "Anadir un enjambre",
        ("*", "Add strings"): "Anadir cuerdas",
        ("*", "Adds a new, independent plexus to the scene. You can have as many as you like, each with its own settings"): "Anade un plexus nuevo e independiente a la escena. Puedes tener todos los que quieras, cada uno con su propia configuracion",
        ("*", "Adds or removes the active source's audio from the Video Sequencer"): "Mete o saca del Video Sequencer el audio de la fuente activa",
        ("*", "Adjust the scene"): "Ajustar la escena",
        ("*", "All the strings on one plane, like a guitar neck"): "Todas en un plano, como el mastil de una guitarra",
        ("*", "Also save the .json"): "Guardar tambien el .json",
        ("*", "Alternates the direction of each copy -low to high, high to low- so they match at the join and the seam does not show"): "Alterna el sentido de cada copia -grave a agudo, agudo a grave- para que en la union coincidan y no se vea la costura",
        ("*", "Alternating"): "Alterna",
        ("*", "Amplitude"): "Amplitud",
        ("*", "An already analyzed .json (by this plugin or by analiza_audio.py)"): "Un .json ya analizado (por este mismo plugin o por analiza_audio.py)",
        ("*", "Analysis FPS"): "FPS del analisis",
        ("*", "Analysis settings"): "Ajustes del analisis",
        ("*", "Analyze audio"): "Analizar un audio",
        ("*", "Analyze audio..."): "Analizar un audio...",
        ("*", "Analyze in stereo"): "Analizar en estereo",
        ("*", "Analyzes both channels separately, on top of the mix. It triples the analysis time and the data size, so it is only worth it if you will use it. If the file is mono it does nothing"): "Analiza los dos canales por separado, ademas de la mezcla. Triplica el tiempo de analisis y el tamano de los datos, asi que solo merece la pena si vas a usarlo. Si el archivo es mono no hace nada",
        ("*", "Angular"): "Angular",
        ("*", "Another ring, but this one takes a whole bar to cross. Used together with the beat ring it gives two layers of rhythm: a fast one and a background one marking where each bar starts"): "Otro anillo, pero este tarda un compas entero en cruzar. Puesto a la vez que el del pulso da dos capas de ritmo: una rapida y una de fondo que marca donde empieza cada compas",
        ("*", "Appearance ratio"): "Ratio de aparicion",
        ("*", "Apply smoothing"): "Aplicar suavizado",
        ("*", "Arc"): "Arco",
        ("*", "Around"): "Alrededor",
        ("*", "At 0 it returns without overshooting, as if braked. Raising it overshoots and oscillates a few times, like a spring"): "A 0 vuelve sin pasarse, como con el freno puesto. Subiendolo se pasa de largo y oscila unas cuantas veces, como un muelle",
        ("*", "At 0 the current blows the same all the time. Raising it, only the particles whose band is sounding get stirred: it boils on the loud hits and goes still in the silences. At 1 the turbulence depends entirely on the music"): "A 0 la corriente sopla siempre igual. Subiendolo, solo se agitan las particulas cuya banda esta sonando: en los golpes fuertes hierve y en los silencios se queda quieta. A 1 la turbulencia depende por completo de la musica",
        ("*", "At 0 the string follows the audio exactly, and goes still the instant it stops. Raising it, the string keeps ringing after the hit and fades out, which is what a plucked string does"): "A 0 la cuerda sigue al audio tal cual y se para en seco. Subiendolo, sigue sonando despues del golpe y se va apagando, que es lo que hace una cuerda pulsada",
        ("*", "At full"): "A tope",
        ("*", "At the edge of the high frequencies"): "Al borde de las frecuencias altas",
        ("*", "At the edge of the low frequencies"): "Al borde de las frecuencias bajas",
        ("*", "Attack (s)"): "Ataque (s)",
        ("*", "Attribute node · Type: Geometry"): "Nodo Attribute · Tipo: Geometry",
        ("*", "Attributes for your shader"): "Atributos para el shader",
        ("*", "Audio"): "Audio",
        ("*", "Audio Viz"): "Audio Viz",
        ("*", "Audio in sequencer"): "Audio en el secuenciador",
        ("*", "Audio removed from the sequencer"): "Audio sacado del secuenciador",
        ("*", "BPM"): "BPM",
        ("*", "Bake"): "Hornear",
        ("*", "Band"): "Banda",
        ("*", "Band from"): "Banda desde",
        ("*", "Band to"): "Banda hasta",
        ("*", "Bands"): "Bandas",
        ("*", "Bands by"): "Bandas por",
        ("*", "Bar marker"): "Marca de compas",
        ("*", "Beat decay (s)"): "Caida del pulso (s)",
        ("*", "Beat kick"): "Golpe del compas",
        ("*", "Beat removed"): "Compas eliminado",
        ("*", "Beat ridge"): "Cresta del compas",
        ("*", "Beats per bar"): "Pulsos por compas",
        ("*", "Beats per minute. The detector fills it in, but you can correct it by hand if you know the track's exact tempo"): "Pulsos por minuto. Lo pone el detector, pero puedes corregirlo a mano si sabes el tempo exacto del tema",
        ("*", "Both are POINT domain, so the shader"): "Ambos son de dominio PUNTO, asi que el",
        ("*", "Both channels mixed, as before"): "Los dos canales mezclados, como hasta ahora",
        ("*", "Both the plexus AND its faces object carry them."): "Los llevan el plexus Y su objeto de caras.",
        ("*", "Bounce"): "Rebote",
        ("*", "Brightness"): "Brillo",
        ("*", "Brightness floor"): "Suelo de brillo",
        ("*", "Brightness on its beat"): "Brillo en su tiempo",
        ("*", "Cap on how many neighbours each point links to, so dense areas do not turn into a blob"): "Tope de vecinos a los que se une cada punto, para que las zonas densas no se conviertan en una mancha",
        ("*", "Centre to rim"): "Del centro al borde",
        ("*", "Change it to get a different scatter"): "Cambiala para obtener otro reparto",
        ("*", "Channel"): "Canal",
        ("*", "Choose an audio file"): "Elige un archivo de audio",
        ("*", "Choose the .json file first"): "Elige primero el archivo .json",
        ("*", "Choose which one to edit:"): "Elige cual editar:",
        ("*", "Circular"): "Circular",
        ("*", "Cleaned up"): "Limpiado",
        ("*", "Cloud"): "Nube",
        ("*", "Colour by intensity"): "Colorear por intensidad",
        ("*", "Column spacing"): "Separacion de columnas",
        ("*", "Columns of separate cubes that light up from the bottom, green to red"): "Columnas de cubos sueltos que se encienden de abajo arriba, de verde a rojo",
        ("*", "Columns per copy"): "Columnas por copia",
        ("*", "Continuous relief. Turn it off to get straight ridges, one per band, equalizer style"): "Relieve continuo. Desactivalo para que salgan crestas rectas, una por banda, en plan ecualizador",
        ("*", "Copies across"): "Copias a lo ancho",
        ("*", "Could not work it out"): "No he podido calcularla",
        ("*", "Create LED equalizer"): "Crear ecualizador de LEDs",
        ("*", "Create bars"): "Crear barras",
        ("*", "Create beat cubes"): "Crear cubos del compas",
        ("*", "Create landscape"): "Crear paisaje",
        ("*", "Create plexus"): "Crear plexus",
        ("*", "Create strings"): "Crear cuerdas",
        ("*", "Create swarm"): "Crear enjambre",
        ("*", "Creates a row of bars hooked to the bands through drivers"): "Crea una fila de barras enganchadas a las bandas mediante drivers",
        ("*", "Creates emission materials whose brightness also follows the band"): "Crea materiales de emision cuyo brillo tambien sigue a la banda",
        ("*", "Cube height"): "Alto del cubo",
        ("*", "Cube size"): "Lado del cubo",
        ("*", "Cube width"): "Ancho del cubo",
        ("*", "Cubes per column. The more there are, the finer the scale and the less retro it looks"): "Cubos por columna. Cuantos mas, mas fina la escala y menos retro",
        ("*", "Curve"): "Curva",
        ("*", "Cylinder"): "Cilindro",
        ("*", "Decay (s)"): "Caida (s)",
        ("*", "Delete everything"): "Borrar todo",
        ("*", "Deletes the analysis image"): "Borra la imagen del analisis",
        ("*", "Deletes the beat properties, their animation and the markers"): "Borra las propiedades del compas, su animacion y los marcadores",
        ("*", "Density of the cloud. Above about 1200 the per-frame rebuild starts to show during playback"): "Densidad de la nube. Por encima de ~1200 la reconstruccion por fotograma empieza a notarse al reproducir",
        ("*", "Depth"): "Fondo",
        ("*", "Detect again"): "Volver a detectar",
        ("*", "Detect beat"): "Detectar compas",
        ("*", "Detect beat on load"): "Detectar el compas al cargar",
        ("*", "Detect from"): "Detectar desde",
        ("*", "Detect the beat first (section 3 of the panel)"): "Detecta primero el compas (seccion 3 del panel)",
        ("*", "Differential spin"): "Giro diferencial",
        ("*", "Direct push"): "Empuje directo",
        ("*", "Disc"): "Disco",
        ("*", "Disorder"): "Desorden",
        ("*", "Distance between the centres of two bars"): "Distancia entre los centros de dos barras",
        ("*", "Distance between the centres of two cubes in the same column. If it is larger than the height, gaps appear between them"): "Distancia entre los centros de dos cubos de la misma columna. Si es mayor que el alto, queda hueco entre ellos",
        ("*", "Draws the whole track as a spectrogram: time across, bands from low to high, and the beats on top. It reflects the smoothing, so you can tune it by eye"): "Dibuja el tema entero como espectrograma: el tiempo a lo ancho, las bandas de grave a agudo, y los pulsos del compas encima. Refleja el suavizado, asi que sirve para ajustarlo mirando",
        ("*", "Driven by"): "Segun",
        ("*", "Dynamic range (dB)"): "Rango dinamico (dB)",
        ("*", "Each band against its own peak: showier"): "Cada banda contra su propio pico: mas vistoso",
        ("*", "Each particle takes a random band. It looks like a real swarm, but you lose the equalizer"): "Cada particula coge una banda al azar. Parece un enjambre de verdad, pero se pierde el ecualizador",
        ("*", "Each point blends the two nearest bands and the surface stays continuous. Turn it off to get plateaus and steps, like a classic equalizer"): "Cada punto mezcla las dos bandas mas cercanas y la superficie queda continua. Desactivalo para que se formen mesetas y escalones, como un ecualizador clasico",
        ("*", "Each point gets a random band"): "Cada punto recibe una banda al azar",
        ("*", "Each string swings up and down only"): "Cada cuerda solo sube y baja",
        ("*", "Eastward (+X)"): "Hacia el este (+X)",
        ("*", "Emission when the band reads 1.0. Above about 5, Blender's AgX view transform washes the colour towards white"): "Emision cuando la banda vale 1.0. Por encima de ~5 el view transform AgX de Blender lava el color hacia el blanco",
        ("*", "Every beat lifts the row it belongs to, and because the rows travel, that ridge moves across the terrain: you see the rhythm receding towards the horizon. Needs the beat detected"): "Cada golpe levanta la fila que le corresponde, y como las filas avanzan, esa cresta viaja por el terreno: se ve el ritmo alejandose hacia el horizonte. Necesita el compas detectado",
        ("*", "FFT window"): "Ventana FFT",
        ("*", "FPS"): "FPS",
        ("*", "Face brightness"): "Brillo de las caras",
        ("*", "Fade the horizon"): "Desvanecer el horizonte",
        ("*", "Fades out the back of the landscape. Without it the relief stops dead in a straight line that gives away that it is a grid"): "Difumina el fondo del paisaje. Sin esto, el relieve se corta en seco con una linea recta que delata que aquello es una rejilla",
        ("*", "Fan"): "Abanico",
        ("*", "Fanned out on an arc, like a harp"): "Abiertas en abanico, como un arpa",
        ("*", "File"): "Archivo",
        ("*", "Fills with triangles the gaps where three points are linked to each other. They go to a separate object, a child of this one, so you can give them their own material without touching the one on the lines"): "Rellena con triangulos los huecos donde tres puntos estan unidos entre si. Van a un objeto separado, hijo de este, para que puedas darles su propio material sin tocar el de las lineas",
        ("*", "Find the beat"): "Buscar el compas",
        ("*", "Fit to size"): "Ajustar al tamano",
        ("*", "Flat"): "Plana",
        ("*", "Flat, galaxy style. This is the one that reads the spectrum best at a glance"): "Plano, tipo galaxia. Es el que mejor lee el espectro de un vistazo",
        ("*", "Floor"): "Suelo",
        ("*", "Force with inertia"): "Fuerza con inercia",
        ("*", "Frames per row"): "Fotogramas por fila",
        ("*", "Frames per second of the analysis. When analyzing here, normally leave it the same as the scene. When loading an outside .json it must match the --fps it was generated with, or it will drift out of sync"): "Fotogramas por segundo del analisis. Al analizar aqui, lo normal es dejarlo igual que la escena. Al cargar un .json de fuera tiene que coincidir con el --fps con el que se genero, o se ira desincronizando",
        ("*", "Frequencies:"): "Frecuencias:",
        ("*", "From"): "De",
        ("*", "From band"): "De la banda",
        ("*", "Gain"): "Ganancia",
        ("*", "Generate faces"): "Generar caras",
        ("*", "Gives this plexus its own copy of the material. Useful after duplicating with Shift+D, which leaves the material shared"): "Da a este plexus una copia propia del material. Util despues de duplicar con Shift+D, que deja el material compartido",
        ("*", "Global"): "Global",
        ("*", "Grid"): "Rejilla",
        ("*", "Grid:"): "Rejilla:",
        ("*", "Grow when sounding"): "Crecer al sonar",
        ("*", "Halves or doubles the tempo. Beat detectors sometimes read a track at twice or half its real tempo: this fixes it in one click"): "Parte o dobla el tempo. Los detectores de ritmo confunden a veces un tema con el doble o la mitad de su tempo: esto lo arregla de un clic",
        ("*", "Hardness"): "Dureza",
        ("*", "Harmonics"): "Armonicos",
        ("*", "Hear this audio"): "Oir este audio",
        ("*", "Highs"): "Agudos",
        ("*", "Highs up to (Hz)"): "Agudos hasta (Hz)",
        ("*", "Horizontal"): "Horizontal",
        ("*", "How abrupt the switch-on is. High = dry and digital, low = the top segment fades in gradually"): "Como de brusco es el encendido. Alto = digital seco, bajo = el segmento de arriba se enciende gradualmente",
        ("*", "How far a point travels when its band reads 1.0"): "Cuanto se desplaza un punto cuando su banda vale 1.0",
        ("*", "How far in it reaches from the edge"): "Cuanto se mete hacia dentro desde la orilla",
        ("*", "How far the cloud leaves its plane. At 0 you get a perfectly flat disc; raising it fattens into a lens"): "Lo que se sale la nube de su plano. A 0 queda un disco perfectamente plano; subiendolo engorda hacia una lenteja",
        ("*", "How fast the current changes. Low reads as alive but calm"): "Lo rapido que cambia la corriente. Bajo se percibe como algo vivo pero tranquilo",
        ("*", "How fast the thickest string wobbles. It gets capped so it never crosses into flicker: below four frames per cycle the eye stops reading movement and sees noise"): "Lo rapido que vibra la cuerda mas gorda. Se acota para que nunca llegue al parpadeo: por debajo de cuatro fotogramas por ciclo el ojo deja de ver movimiento y ve ruido",
        ("*", "How high the relief rises when the band reads 1.0"): "Cuanto se levanta el relieve cuando la banda vale 1.0",
        ("*", "How it is drawn:"): "Como se traza:",
        ("*", "How it reacts to the frequencies:"): "Como reacciona a las frecuencias:",
        ("*", "How long 'pulso' takes to fall from 1 to 0 after each beat"): "Cuanto tarda 'pulso' en bajar de 1 a 0 tras cada golpe",
        ("*", "How long a string keeps sounding after being plucked"): "Cuanto sigue sonando una cuerda despues de pulsarla",
        ("*", "How long it takes to come back after a shove. Short = nervous and tight to the beat; long = heavy, the particles keep moving after the hit has passed"): "Lo que tarda en regresar tras un empujon. Corto = nervioso y pegado al ritmo; largo = pesado, las particulas siguen moviendose cuando el golpe ya paso",
        ("*", "How loud each vertex's band is right now"): "Cuanto suena la banda de cada vertice ahora mismo",
        ("*", "How many bands the spectrum is split into"): "En cuantas bandas se reparte el espectro",
        ("*", "How many dB below the peak count as 0. Less = more contrast"): "Cuantos dB por debajo del pico se consideran 0. Menos = mas contraste",
        ("*", "How many moments of the past are visible at once. More rows = a deeper horizon and a denser mesh"): "Cuantos instantes del pasado se ven a la vez. Mas filas = horizonte mas profundo y malla mas densa",
        ("*", "How many there are. A few thousand read as individual particles; from tens of thousands on it reads as dust, and the viewport slows down"): "Cuantas hay. Unas miles se distinguen de una en una; a partir de decenas de miles se lee como polvo, y el visor va mas lento",
        ("*", "How many wave cycles run across the bank of strings. This is what turns a pile of independent wiggles into one readable wave travelling through them. 0 makes them all move together"): "Cuantos ciclos de onda recorren el banco de cuerdas. Esto es lo que convierte un monton de meneos sueltos en una sola onda que se lee viajando por ellas. Con 0 se mueven todas a la vez",
        ("*", "How much a particle swells when its band sounds. At 0 they are all the same size and only the brightness changes"): "Cuanto engorda una particula cuando su banda suena. A 0 todas miden igual y solo cambia el brillo",
        ("*", "How much each bar jumps on every beat, on top of whatever its band does. Needs the beat detected"): "Cuanto sube cada barra de golpe en cada pulso, ademas de lo que haga su banda. Necesita el compas detectado",
        ("*", "How much each part of the spectrum rules:"): "Cuanto manda cada zona del espectro:",
        ("*", "How much faster the inner ones go than the outer ones. At 0 the cloud spins like a solid, which reads as rigid; raised, it coils by itself and looks like a galaxy"): "Cuanto mas rapido van las de dentro que las de fuera. A 0 la nube gira como un solido, que se lee como algo rigido; subido se enrosca sola y parece una galaxia",
        ("*", "How much faster the thinnest string wobbles than the thickest, in octaves. 2 means four times faster"): "Cuanto mas rapido vibra la cuerda mas fina que la mas gorda, en octavas. 2 son cuatro veces mas rapido",
        ("*", "How much it fades"): "Cuanto se desvanece",
        ("*", "How much it grows"): "Cuanto crece",
        ("*", "How much of the back fades out, from 0 to 1"): "Que parte del fondo se difumina, de 0 a 1",
        ("*", "How much of the spectrum it covers. At 1 it is a straight ridge from side to side, which looks like a step; lowering it concentrates on the lows and leaves a swell born where the kick is"): "Cuanto del espectro abarca. Con 1 es una cresta recta de lado a lado, que parece un escalon; bajandolo se concentra en los graves y queda una loma que nace donde esta el bombo",
        ("*", "How much the cube stretches on its beat. 1.5 = one and a half cubes taller"): "Cuanto se estira el cubo en su tiempo. 1.5 = un cubo y medio mas alto",
        ("*", "How much the lows rule the movement AND the brightness. At 0 the low particles neither move nor light up"): "Cuanto mandan los graves sobre el movimiento Y sobre el brillo. A 0 las particulas graves ni se mueven ni se encienden",
        ("*", "How much the quiet particles glow. At 0 they disappear and you only see what sounds; raised, the whole cloud is always visible"): "Lo que iluminan las particulas calladas. A 0 desaparecen y solo se ve lo que suena; subido se ve siempre la nube entera",
        ("*", "How much the strings splay out on the arc layout"): "Cuanto se abren las cuerdas en la disposicion de arco",
        ("*", "How much the waves light things up as they pass, on top of pushing"): "Cuanto encienden las ondas al pasar, aparte de empujar",
        ("*", "How much time each row covers. At 1 the relief advances one row per frame; at 2 it advances half a row (slower, but you see twice the history); at 0.5 it advances two (faster and with more detail)"): "Cuanto tiempo cubre cada fila. Con 1 el relieve avanza una fila por fotograma; con 2 avanza media (mas lento, pero se ve el doble de historia); con 0.5 avanza dos (mas rapido y con mas detalle)",
        ("*", "How tall the bar is in silence (so it does not vanish)"): "Cuanto mide la barra en silencio (para que no desaparezca)",
        ("*", "How tall the bar is when its band reads 1.0"): "Cuanto mide la barra cuando la banda vale 1.0",
        ("*", "How wide a string opens when its band is at full"): "Cuanto se abre una cuerda cuando su banda esta a tope",
        ("*", "Import an audio file first"): "Importa primero un audio",
        ("*", "Import audio"): "Importar audio",
        ("*", "In fractions of a cell: 0.5 would be a whole cell painted"): "En fracciones de celda: 0.5 seria una celda entera pintada",
        ("*", "In stereo you get twice as many bars, mirrored: lows in the centre and highs at the edges, left channel on the left"): "En estereo se hacen el doble de barras, en espejo: los graves al centro y los agudos a los extremos, el canal izquierdo a la izquierda",
        ("*", "In stereo you get twice as many columns, mirrored"): "En estereo se hacen el doble de columnas, en espejo",
        ("*", "In stereo, the left half of the cloud follows the left channel and the right half the right one, blending through the centre"): "En estereo, la mitad izquierda de la nube sigue al canal izquierdo y la derecha al derecho, fundiendose por el centro",
        ("*", "In stereo, the left side of the terrain follows the left channel and the right side the right one"): "En estereo, el lado izquierdo del terreno sigue al canal izquierdo y el derecho al derecho",
        ("*", "In the SWARM, type: Instancer"): "En el ENJAMBRE, tipo: Instancer",
        ("*", "Instead of creating a new source, swaps the active source's audio while keeping its name and everything that already depends on it"): "En vez de crear una fuente nueva, cambia el audio de la fuente activa conservando su nombre y todo lo que ya dependa de ella",
        ("*", "Intensity"): "Intensidad",
        ("*", "Interpolate between bands"): "Interpolar entre bandas",
        ("*", "It also carries a third one:"): "Ademas lleva un tercero:",
        ("*", "It also swings sideways, whipping in a spiral"): "Tambien se mueve de lado, latigueando en espiral",
        ("*", "It usually looks better wider than the beat one: moving so slowly, a thin ring is left as a thread you can barely see move"): "Suele quedar mejor mas ancho que el del pulso: al ir tan despacio, un anillo fino se queda en un hilo que apenas se ve moverse",
        ("*", "JSON file"): "Archivo JSON",
        ("*", "Just the grid wires, retro style"): "Solo los hilos de la rejilla, en plan retro",
        ("*", "Kick (whole cloud)"): "Golpe (toda la nube)",
        ("*", "Large = whole areas of the cloud move together, like a current. Small = every particle on its own, and the jitter comes back"): "Grande = zonas enteras de la nube se mueven juntas, como una corriente. Pequeno = cada particula por su lado, y vuelve el temblor",
        ("*", "Layout"): "Disposicion",
        ("*", "Layout:"): "Disposicion:",
        ("*", "Leaves a copy with the animation baked into shape keys, which works without the extension: for sending the .blend to a render farm or to someone who does not have it. The original is left alone"): "Deja una copia con la animacion metida en claves de forma, que funciona sin la extension: para mandar el .blend a una granja de render o a alguien que no la tenga. El original no se toca",
        ("*", "Leaves the analysis in a .json next to the audio, to reuse without analyzing again or to pass on to someone else"): "Deja el analisis en un .json junto al audio, para reutilizarlo sin volver a analizar o pasarselo a otra persona",
        ("*", "Left"): "Izquierdo",
        ("*", "Left only"): "Solo el izquierdo",
        ("*", "Length"): "Largo",
        ("*", "Lifts the whole terrain so the valleys are not left flat"): "Levanta el terreno entero para que los valles no queden planos",
        ("*", "Line colour:"): "Color de las lineas:",
        ("*", "Line thickness"): "Grosor de linea",
        ("*", "Link distance"): "Distancia de union",
        ("*", "Links per point"): "Conexiones por punto",
        ("*", "Lit brightness"): "Brillo encendido",
        ("*", "Load JSON"): "Cargar JSON",
        ("*", "Load an audio file first"): "Carga primero un audio",
        ("*", "Look"): "Aspecto",
        ("*", "Look:"): "Aspecto:",
        ("*", "Looks for the tempo right after analyzing, without you pressing anything. It costs a few tenths of a second. If the track has no clear rhythm nothing breaks: it says so and carries on"): "Busca el tempo nada mas analizar, sin tener que pulsar nada. Cuesta unas decimas de segundo. Si el tema no tiene un ritmo claro no pasa nada: lo dice y sigue",
        ("*", "Loose points inside a scene object; they move radially from its centre"): "Puntos sueltos por dentro de un objeto de la escena; se mueven en radial desde su centro",
        ("*", "Loose points inside a spherical volume"): "Puntos sueltos dentro de un volumen esferico",
        ("*", "Lowest string (Hz)"): "Cuerda mas grave (Hz)",
        ("*", "Lows"): "Graves",
        ("*", "Lows from (Hz)"): "Graves desde (Hz)",
        ("*", "Lows in the centre and highs outside. The spectrum reads like a dartboard"): "Los graves en el centro y los agudos fuera. El espectro se lee como una diana",
        ("*", "Lows/highs balance"): "Balance graves/agudos",
        ("*", "Make material single-user"): "Desvincular material",
        ("*", "Make room"): "Hacerse sitio",
        ("*", "Makes this plexus active so you can edit its settings in the panel"): "Hace activo este plexus para poder editar sus ajustes en el panel",
        ("*", "Marker width"): "Ancho de la marca",
        ("*", "Maximum brightness"): "Brillo maximo",
        ("*", "Maximum height"): "Altura maxima",
        ("*", "Mids"): "Medios",
        ("*", "Minimum height"): "Altura minima",
        ("*", "Mirror copies"): "Copias en espejo",
        ("*", "Mixed"): "Mezcladas",
        ("*", "Model"): "Modelo",
        ("*", "Model surface"): "Piel de un modelo",
        ("*", "Model volume"): "Interior de un modelo",
        ("*", "Mono"): "Mono",
        ("*", "Mountain height"): "Altura de las montanas",
        ("*", "Movement:"): "Movimiento:",
        ("*", "Multiplies the whole height. Above 1 the peaks flatten against the ceiling, which is a useful effect too"): "Multiplica toda la altura. Por encima de 1 las cumbres se aplanan contra el techo, que tambien es un efecto util",
        ("*", "Mutes or unmutes this audio's strip in the sequencer. When you analyze, the file is always added; this only decides whether you hear it. Turning it on also enables audio while scrubbing"): "Silencia o deja sonar la pista de este audio en el secuenciador. Al analizar, el archivo se mete siempre; esto solo decide si suena. Activarlo enciende tambien el sonido al arrastrar el cursor",
        ("*", "Narrow = a whip crack running through the cloud; wide = a tide"): "Estrecho = un latigazo que recorre la nube; ancho = una marea",
        ("*", "Needs numpy and it is not available"): "Necesita numpy y no esta disponible",
        ("*", "Never cross"): "Que no se crucen nunca",
        ("*", "No audio of its own: uses the active one"): "Sin audio propio: usa el activo",
        ("*", "No smoothing"): "Sin suavizado",
        ("*", "Normalize"): "Normalizar",
        ("*", "Northward (+Y)"): "Hacia el norte (+Y)",
        ("*", "Octaves up"): "Octavas arriba",
        ("*", "Offset (frames)"): "Desfase (fotogramas)",
        ("*", "On every beat a few extra segments light up, as if the needle jumped. Needs the beat detected"): "En cada pulso se encienden segmentos de mas, como si la aguja pegara un salto. Necesita el compas detectado",
        ("*", "On every beat the whole cloud shoves outwards. It is a uniform pulse: you notice it, but it looks more like the object swelling than like rhythm. Needs the beat detected"): "En cada pulso la nube entera pega un empujon hacia fuera. Es un latido uniforme: se nota, pero parece mas que el objeto engorda que un ritmo. Necesita el compas detectado",
        ("*", "On the side of"): "En el lado de",
        ("*", "One string per band, held at both ends and vibrating like a guitar's. The louder its band, the wider it opens"): "Una cuerda por banda, sujeta por los dos extremos y vibrando como las de una guitarra. Cuanto suena su banda, mas se abre",
        ("*", "Opacity"): "Opacidad",
        ("*", "Opens an audio file, analyzes it right here and creates the source. Needs no outside program: it uses the audio decoder and the ffmpeg Blender already ships"): "Abre un archivo de audio, lo analiza aqui mismo y crea la fuente. No necesita ningun programa de fuera: usa el decodificador y el ffmpeg que Blender ya trae",
        ("*", "Output to use from the Attribute node:"): "Salida a usar del nodo Attribute:",
        ("*", "Particles"): "Particulas",
        ("*", "Peaks"): "Cumbres",
        ("*", "Per band"): "Por banda",
        ("*", "Pick a model (sphere in the meantime)"): "Elige un modelo (mientras, esfera)",
        ("*", "Places a marker at the start of every bar, so you can see it while scrubbing"): "Pone una marca al principio de cada compas, para verlo al hacer scrub",
        ("*", "Places the particle according to what sounds NOW: if the audio jumps, it jumps. The easiest to read, but with busy music it jitters"): "Coloca la particula segun lo que suena AHORA: si el audio pega un salto, ella pega el salto. Es el mas directo de leer, pero con musica movida tiembla",
        ("*", "Playback FPS"): "FPS de reproduccion",
        ("*", "Point 1 band 0, point 2 band 1... they interleave"): "Punto 1 banda 0, punto 2 banda 1... se entremezclan",
        ("*", "Point size"): "Tamano del punto",
        ("*", "Points"): "Puntos",
        ("*", "Points along each string. Below about 32 the wave shows its corners; above 200 it costs more and looks the same"): "Puntos de cada cuerda. Por debajo de 32 se le notan las esquinas a la onda; por encima de 200 cuesta mas y se ve igual",
        ("*", "Points in a circle breathing outwards"): "Puntos en circulo que respiran hacia fuera",
        ("*", "Points spread over the surface of a scene object; they move outwards along the normal, like a breathing skin"): "Puntos repartidos por la superficie de un objeto de la escena; se mueven hacia fuera siguiendo la normal, como una piel que respira",
        ("*", "Points spread over the surface of a sphere"): "Puntos repartidos por la superficie de una esfera",
        ("*", "Preset: LED equalizer"): "Preset: ecualizador LED",
        ("*", "Preset: bars"): "Preset: barras",
        ("*", "Preset: beat cubes"): "Preset: el compas en cubos",
        ("*", "Preset: orbital swarm"): "Preset: enjambre orbital",
        ("*", "Preset: plexus"): "Preset: plexus",
        ("*", "Preset: scrolling landscape"): "Preset: paisaje que avanza",
        ("*", "Preset: strings"): "Preset: cuerdas",
        ("*", "Radial"): "Radial",
        ("*", "Radius"): "Radio",
        ("*", "Raise 'Links per point' to 6-10 so that"): "Sube 'Conexiones por punto' a 6-10 para que",
        ("*", "Raise the step above the height to leave a gap"): "Sube el paso por encima del alto para que haya hueco",
        ("*", "Raises 'Make room' to whatever guarantees no string can reach its neighbour, however wide it swings. Turn it off if you want them to weave through each other"): "Sube 'Hacerse sitio' a lo que garantiza que ninguna cuerda pueda alcanzar a su vecina, por mucho que se abra. Desactivalo si quieres que se entrelacen",
        ("*", "Random"): "Aleatoria",
        ("*", "Re-import the JSON to enable it"): "Reimporta el JSON para activarlo",
        ("*", "Reactive emissive material"): "Material emisivo reactivo",
        ("*", "Reacts to the left channel only"): "Reacciona nada mas al canal izquierdo",
        ("*", "Reacts to the right channel only"): "Reacciona nada mas al canal derecho",
        ("*", "Reads the JSON and creates a new audio source. You can have several in one scene, each with its own file"): "Lee el JSON y crea una fuente de audio nueva. Puedes tener varias en la misma escena, cada una con su archivo",
        ("*", "Rebuilds the animation from the original values. You rarely need this: it happens by itself when you move the sliders"): "Recalcula la animacion desde los valores originales del JSON. Normalmente no hace falta: se aplica solo al mover los deslizadores",
        ("*", "Redistributes the relief. Below 1 it lifts the valleys and you get terrain everywhere; above 1 it flattens everything but the peaks and you get lone mountains on a plain"): "Reparte el relieve. Por debajo de 1 levanta los valles y sale terreno por todas partes; por encima de 1 aplasta todo menos los picos y quedan montanas sueltas sobre un llano",
        ("*", "Regenerate points"): "Regenerar puntos",
        ("*", "Remove beat"): "Quitar compas",
        ("*", "Remove view"): "Quitar la vista",
        ("*", "Removes the Empty, the bars, the materials and the generated animation"): "Elimina el Empty, las barras, los materiales y la animacion generados",
        ("*", "Repeat sideways:"): "Repetir a los lados:",
        ("*", "Repeats the landscape sideways to fill more screen. Each copy is as wide as 'Width' says, so the total grows with them"): "Repite el paisaje a los lados para llenar mas pantalla. Cada copia mide lo que diga 'Ancho', asi que el total crece con ellas",
        ("*", "Replace"): "Reemplazar",
        ("*", "Replace this source's audio"): "Reemplazar el audio de esta fuente",
        ("*", "Replace with JSON"): "Reemplazar con JSON",
        ("*", "Resolution across ONE copy. The bands are interpolated between columns"): "Resolucion a lo ancho de UNA copia. Las bandas se interpolan entre columnas",
        ("*", "Resting brightness"): "Brillo en reposo",
        ("*", "Restore audio strip"): "Recuperar el audio en la pista",
        ("*", "Return time"): "Tiempo de vuelta",
        ("*", "Rhythm:"): "Ritmo:",
        ("*", "Ridge width"): "Ancho de la cresta",
        ("*", "Right"): "Derecho",
        ("*", "Right only"): "Solo el derecho",
        ("*", "Ring"): "Resonancia",
        ("*", "Ring time"): "Duracion",
        ("*", "Rows (time)"): "Filas (tiempo)",
        ("*", "Samples per FFT. Larger = more detail in the lows but smearier transients. It is the same trade-off as shutter speed against motion blur"): "Muestras por FFT. Mas grande = mas detalle en los graves pero transitorios mas emborronados. Es el mismo dilema que velocidad de obturacion contra motion blur",
        ("*", "Scatters the points again. Needed if you have moved, scaled or edited the model they come from: the plexus is born on top of it but does not follow it afterwards"): "Vuelve a repartir los puntos. Necesario si has movido, escalado o editado el modelo del que salen: el plexus nace encima de el pero despues no lo persigue",
        ("*", "Scatters the strings' phases on top of the wave. At 0 the movement is perfectly ordered; raise it for something more alive, and at 1 each string goes entirely its own way"): "Reparte las fases de las cuerdas por encima de la onda. A 0 el movimiento es perfectamente ordenado; subelo para algo mas vivo, y a 1 cada cuerda va totalmente a su aire",
        ("*", "Searches for the tempo again. It runs by itself when you load audio; this is for repeating it after changing which bands are looked at"): "Vuelve a buscar el tempo. Se hace solo al cargar un audio; esto sirve para repetirlo despues de tocar las bandas que se miran",
        ("*", "Seconds a peak takes to FALL from 1 to 0 at most. 0 = instant fall (follows the audio exactly). More seconds = a longer tail, like a compressor's release"): "Segundos que tarda un pico en BAJAR de 1 a 0 como mucho. 0 = caida instantanea (sigue al audio tal cual). Mas segundos = cola mas larga, como el release de un compresor",
        ("*", "Seconds the value takes to RISE from 0 to 1 at most. 0 = instant rise, which is usually what you want so the hit lands sharp. Raise it to suggest weight or inertia"): "Segundos que tarda el valor en SUBIR de 0 a 1 como mucho. 0 = subida instantanea, que suele ser lo que quieres para que el golpe entre seco. Subelo para dar sensacion de peso o inercia",
        ("*", "Seed"): "Semilla",
        ("*", "Segments"): "Segmentos",
        ("*", "Select a plexus"): "Selecciona un plexus",
        ("*", "Select a plexus, a landscape or a swarm"): "Selecciona un plexus, un paisaje o un enjambre",
        ("*", "Select a plexus, a landscape, a swarm or strings"): "Selecciona un plexus, un paisaje, un enjambre o unas cuerdas",
        ("*", "Select plexus"): "Seleccionar plexus",
        ("*", "Sets attack and decay to 0 and returns the animation to the original values"): "Pone ataque y caida a 0 y devuelve la animacion a los valores originales",
        ("*", "Sets the fps and the timeline range to match the audio"): "Pone los fps y el rango de la linea de tiempo para que cuadren con el audio",
        ("*", "Sets the link distance from how far apart the points actually are, so you get a reasonable mesh without guessing"): "Pone la distancia de union a partir de lo separados que estan los puntos, para que salga una malla razonable sin ir a tientas",
        ("*", "Shape"): "Forma",
        ("*", "Shape the relief:"): "Moldear el relieve:",
        ("*", "Show analysis"): "Ver el analisis",
        ("*", "Show channel"): "Ver el canal",
        ("*", "Size"): "Tamano",
        ("*", "Smoothing is adjusted afterwards, live"): "El suavizado se ajusta luego, en vivo",
        ("*", "Solid"): "Solido",
        ("*", "Solid + wireframe"): "Solido + malla",
        ("*", "Southward (-Y)"): "Hacia el sur (-Y)",
        ("*", "Spacing"): "Separacion",
        ("*", "Speed:"): "Velocidad:",
        ("*", "Sphere"): "Esfera",
        ("*", "Spin"): "Giro",
        ("*", "Spin:"): "Giro:",
        ("*", "Start frame"): "Fotograma inicial",
        ("*", "Stereo"): "Estereo",
        ("*", "Stirred by the audio"): "La agita el audio",
        ("*", "Surface opacity"): "Opacidad de la superficie",
        ("*", "Swing"): "Vaiven",
        ("*", "Swirl size"): "Tamano del remolino",
        ("*", "Swirl speed"): "Velocidad del remolino",
        ("*", "The band depends on height: lows at the bottom, highs at the top"): "La banda depende de la altura: graves abajo, agudos arriba",
        ("*", "The band depends on the X position, like a spectrum laid down"): "La banda depende de la posicion en X, como un espectro tumbado",
        ("*", "The band depends on the distance to the vertical axis"): "La banda depende de la distancia al eje vertical",
        ("*", "The bands go around the centre"): "Las bandas dan la vuelta alrededor del centro",
        ("*", "The cloud:"): "La nube:",
        ("*", "The cubes that are not due do not disappear: they stay dim"): "Los cubos que no tocan no desaparecen: se quedan tenues",
        ("*", "The face takes its colour from what its vertices sound like, interpolated. Off, it stays a flat colour"): "La cara toma color segun lo que suenen sus vertices, interpolado. Apagado, queda de un color plano",
        ("*", "The file is too short"): "El archivo es demasiado corto",
        ("*", "The highs"): "Los agudos",
        ("*", "The left channel only"): "Solo el canal izquierdo",
        ("*", "The left side of the object follows the left channel and the right side the right one"): "El lado izquierdo del objeto sigue al canal izquierdo y el derecho al derecho",
        ("*", "The lows"): "Los graves",
        ("*", "The mesh must be closed"): "La malla debe estar cerrada",
        ("*", "The mix"): "La mezcla",
        ("*", "The relief comes from afar and approaches the viewer"): "El relieve viene de lejos y se acerca al observador",
        ("*", "The relief moves away from the viewer"): "El relieve se aleja del observador",
        ("*", "The right channel only"): "Solo el canal derecho",
        ("*", "The rim only, with an empty centre"): "Solo el borde, con el centro vacio",
        ("*", "The same --fps you used in analiza_audio.py for THIS file"): "Los mismos --fps que usaste en analiza_audio.py para ESTE archivo",
        ("*", "The same for the highs"): "Lo mismo para los agudos",
        ("*", "The same for the middle of the spectrum"): "Lo mismo para la zona central del espectro",
        ("*", "The scene object the points are taken from. It is read with its modifiers applied, so you can use Subdivision, Remesh..."): "El objeto de la escena del que se sacan los puntos. Se lee con sus modificadores aplicados, asi que puedes usar Subdivision, Remesh...",
        ("*", "The scene range is backwards"): "El rango de la escena esta al reves",
        ("*", "The second layer, slower: it takes a whole bar to cross"): "La segunda capa, mas lenta: tarda un compas entero en cruzar",
        ("*", "The spectrum goes around the circle, like the hours on a clock"): "El espectro da la vuelta al circulo, como las horas de un reloj",
        ("*", "The surface only"): "Solo la superficie",
        ("*", "The surface with the grid drawn on top"): "La superficie con la rejilla marcada encima",
        ("*", "There is no active source"): "No hay ninguna fuente activa",
        ("*", "There is no active source to replace"): "No hay ninguna fuente activa que reemplazar",
        ("*", "Thickness"): "Grosor",
        ("*", "This preset needs numpy and it is not available"): "Este preset necesita numpy y no esta disponible",
        ("*", "This source does not keep the original values. Import the JSON again"): "Esta fuente no guarda los valores originales. Vuelve a importar el JSON",
        ("*", "This source does not know which file it came from (happens with ones loaded from .json)"): "Esta fuente no sabe de que archivo viene (pasa con las cargadas desde .json)",
        ("*", "Timeline markers"): "Marcadores en la linea de tiempo",
        ("*", "Travels"): "Avanza",
        ("*", "Travels to the left"): "Avanza hacia la izquierda",
        ("*", "Travels to the right"): "Avanza hacia la derecha",
        ("*", "Treats every hit as a shove on something with weight: it eases out and returns by itself. Far subtler. This is how far a particle travels with its band at full and sustained. You can mix it with the direct push, or use it alone by dropping that to zero"): "Trata cada golpe como un empujon sobre algo que pesa: sale despacio y vuelve solo. Mucho mas sutil. Es lo que se desplaza una particula con su banda sonando a tope y sostenida. Se puede mezclar con el empuje directo, o usarlo solo bajando aquel a cero",
        ("*", "Turbulence"): "Turbulencia",
        ("*", "Turbulence:"): "Turbulencia:",
        ("*", "Turns per second. Negative spins the other way"): "Vueltas por segundo. En negativo gira al reves",
        ("*", "Two points link if they are closer than this. It is the control that changes the look the most: low = loose points, high = a tangle"): "Dos puntos se unen si estan mas cerca que esto. Es el control que mas cambia el aspecto: bajo = puntos sueltos, alto = maraña",
        ("*", "Unchecked, it bakes only from the current frame to the end"): "Desmarcado, hornea solo desde el fotograma actual hasta el final",
        ("*", "Unlit brightness"): "Brillo apagado",
        ("*", "Unlit segments do not disappear: they stay dim, like real LEDs"): "Los segmentos apagados no desaparecen: quedan tenues, como los LEDs de verdad",
        ("*", "Used only to work out where flicker starts. Leave it at your scene's frame rate"): "Solo se usa para saber donde empieza el parpadeo. Dejalo igual que los fps de tu escena",
        ("*", "Valleys"): "Valles",
        ("*", "Values on this frame"): "Valores en este fotograma",
        ("*", "Vertical"): "Vertical",
        ("*", "Vertical step"): "Paso vertical",
        ("*", "Vibration:"): "Vibracion:",
        ("*", "Wave flash"): "Destello de la onda",
        ("*", "Wave per bar"): "Onda por compas",
        ("*", "Wave per beat"): "Onda por pulso",
        ("*", "Waves across"): "Ondas a lo ancho",
        ("*", "Westward (-X)"): "Hacia el oeste (-X)",
        ("*", "What fraction of the possible triangles gets filled. 1 = all of them (a closed membrane), 0.3 = loose patches. The draw is stable: a given triangle either appears or not, always the same, it does not flicker"): "Que fraccion de los triangulos posibles se rellena. 1 = todos (membrana cerrada), 0.3 = parches sueltos. El sorteo es estable: un triangulo concreto sale o no sale siempre igual, no parpadea",
        ("*", "What the silent strings glow. At 0 they vanish and you only see what sounds"): "Lo que iluminan las cuerdas calladas. A 0 desaparecen y solo se ve lo que suena",
        ("*", "What you see there are instanced spheres,"): "Lo que ves ahi son bolitas instanciadas,",
        ("*", "When silent"): "En silencio",
        ("*", "Where each vertex sits in the spectrum: low or high"): "Donde esta cada vertice en el espectro: grave o agudo",
        ("*", "Where the first beat falls. Move it if the rhythm runs ahead of or behind the music"): "Donde cae el primer pulso. Muevelo si el ritmo va adelantado o atrasado respecto a la musica",
        ("*", "Which Blender frame corresponds to frame 0 of the audio"): "A que fotograma de Blender corresponde el fotograma 0 del audio",
        ("*", "Which attribute feeds the gradient on the faces"): "Que atributo alimenta el degradado de las caras",
        ("*", "Which audio draws the relief"): "Que audio dibuja el relieve",
        ("*", "Which audio source drives these strings"): "Que fuente de audio mueve estas cuerdas",
        ("*", "Which audio source drives this plexus. If you have several loaded, each plexus can listen to a different one"): "Que fuente de audio mueve este plexus. Si tienes varias cargadas, cada plexus puede escuchar una distinta",
        ("*", "Which audio source drives this swarm"): "Que fuente de audio mueve este enjambre",
        ("*", "Which audio the smoothing and the preset buttons act on"): "Sobre que audio actuan el suavizado y los botones de crear presets",
        ("*", "Which bands are looked at to find the rhythm. The low ones usually carry the kick; if the track has no drums, try all of them"): "Bandas que se miran para encontrar el ritmo. Las graves suelen llevar el bombo; si el tema no tiene bateria, prueba con todas",
        ("*", "Which edge the marker goes on. By default the highs, because the beat ridge concentrates on the lows and they would cover each other"): "En que orilla va la marca. Por defecto en los agudos, porque la cresta del pulso se concentra en los graves y se taparian",
        ("*", "Which frequencies drive it:"): "Que frecuencias lo mueven:",
        ("*", "Which strings:"): "Que cuerdas:",
        ("*", "Whole scene range"): "Todo el rango de la escena",
        ("*", "Width"): "Ancho",
        ("*", "Wire thickness"): "Grosor de los hilos",
        ("*", "Wireframe"): "Malla",
        ("*", "With 'Solid + wireframe', how visible the surface is between the wires"): "Con 'Solido + malla', cuanto se ve la superficie entre los hilos",
        ("*", "Wrapped around a circle; the camera can go inside"): "Envolviendo un circulo; la camara puede meterse dentro",
        ("*", "affects movement and brightness"): "afecta al movimiento y al brillo",
        ("*", "all three at 1: untouched"): "los tres a 1: sin tocar",
        ("*", "and the values live on the point that"): "y los valores viven en el punto que las",
        ("*", "av_intensidad"): "av_intensidad",
        ("*", "av_intensity"): "av_intensity",
        ("*", "av_level"): "av_level",
        ("*", "av_nivel"): "av_nivel",
        ("*", "both at once: they add up"): "los dos a la vez: se suman",
        ("*", "capped, or it would flicker"): "acotado, o parpadearia",
        ("*", "corners, and every line between its two ends."): "esquinas, y cada linea entre sus dos puntas.",
        ("*", "detect the beat above to use this"): "detecta el compas arriba para usarlo",
        ("*", "follows the audio exactly"): "sigue al audio tal cual",
        ("*", "info"): "info",
        ("*", "instances them, not on the sphere. With 'Geometry'"): "instancia, no en la bolita. Con 'Geometry'",
        ("*", "interpolates them across the face: every"): "shader los interpola por la cara: cada",
        ("*", "mono: tick 'Analyze in stereo' when loading"): "mono: marca 'Analizar en estereo' al cargar",
        ("*", "no audio: it came from a .json"): "sin audio: viene de un .json",
        ("*", "no beat: not found, or you removed it"): "sin compas: no lo encontro, o lo quitaste",
        ("*", "numpy is required and not available"): "Hace falta numpy y no esta disponible",
        ("*", "open it in an image editor to see it large"): "abrelo en un editor de imagenes para verlo grande",
        ("*", "or load an already analyzed .json:"): "o cargar un .json ya analizado:",
        ("*", "they would all come out the same colour."): "saldrian todas del mismo color.",
        ("*", "to"): "hasta",
        ("*", "triangle comes out graded between its three"): "triangulo sale degradado entre sus tres",
        ("*", "triangles close and a membrane appears"): "se cierren triangulos y haya membrana",
        ("*", "try other bands and search again"): "prueba con otras bandas y vuelve a buscar",
        ("*", "with both at zero it does not react to the audio"): "con ambos a cero no reacciona al audio",
        ("*", "x0.5 / x2"): "x0.5 / x2",
        ("*", "x2"): "x2",
    },
}
